<a href="https://colab.research.google.com/github/Arshadfarazusmani/Data_Science_AI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy


## Numpy indexing and Slicing of Vectors

In [ ]:
import numpy as np

In [ ]:
arr= np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[8]

np.int64(19)

In [ ]:
arr[2:5]

array([13, 14, 15])

In [ ]:
arr[5:]

array([16, 17, 18, 19, 20])

In [ ]:
arr[:6]

array([11, 12, 13, 14, 15, 16])

In [ ]:
arr[::2]

array([11, 13, 15, 17, 19])

In [ ]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

## Matrix sclicing

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[5]

array([26, 27, 28, 29, 30])

In [ ]:
arr[0,0]

np.int64(1)

In [ ]:
arr[5,2]

np.int64(28)

### Metrix Sclicing

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
scliced1=arr[0:2,1:3]
scliced1

array([[2, 3],
       [7, 8]])

In [ ]:
scliced2=arr[3:,3:]
scliced2

array([[19, 20],
       [24, 25],
       [29, 30]])

## Boolean indexing

In [ ]:
arr=np.array(1,11)

TypeError: Cannot interpret '11' as a data type

In [ ]:
arr2=np.arange(1,11)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr2[bool_index]

array([ 2,  4,  6,  8, 10])

In [ ]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_index=arr2 %2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

# Array operations

In [ ]:
import numpy as np


In [ ]:
arr1= np.array([1,2,3,4,5])
arr2= np.array([6,7,8,9,10])

sum_arr=arr1+arr2
sum_arr

array([ 7,  9, 11, 13, 15])

In [ ]:
sum_arr.sort()

In [ ]:
sum_arr

array([ 7,  9, 11, 13, 15])

In [ ]:
sum_arr*2

array([14, 18, 22, 26, 30])

In [ ]:
sum_arr

array([ 7,  9, 11, 13, 15])

In [ ]:
arr1-arr2

array([-5, -5, -5, -5, -5])

In [ ]:
arr1*arr2

array([ 6, 14, 24, 36, 50])

In [ ]:
arr1//arr2

array([0, 0, 0, 0, 0])

In [ ]:
arr1**arr2

array([      1,     128,    6561,  262144, 9765625])

## Broadcasting

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1

In [ ]:
arr1+10

array([11, 12, 13, 14, 15])

In [ ]:
arr3=np.arange(0,30).reshape(6,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr+20

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
arr3+50

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79]])

# Deep and Shallow copies

In [ ]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
sclice= a[:5]
sclice


array([1, 2, 3, 4, 5])

In [ ]:
sclice

array([1, 2, 3, 4, 5])

In [ ]:
sclice*10

array([10, 20, 30, 40, 50])

In [ ]:
sclice

array([1, 2, 3, 4, 5])

In [ ]:
sclice=sclice*10
sclice

array([100, 200, 300, 400, 500])

In [ ]:
sclice

array([1, 2, 3, 4, 5])

In [ ]:
sclice=sclice*10
sclice

array([10, 20, 30, 40, 50])

# Matrix